version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: service-db
    environment:
      POSTGRES_DB: "servicedb"
      POSTGRES_USER: "servicedb_user"
      POSTGRES_PASSWORD: "servicedb_passwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servicedb_user -d servicedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  web-service:
    image: mgcrp/hw2_web:latest
    container_name: service-web
    environment:
       POSTGRES_HOST: "service-db"
       POSTGRES_DB: "servicedb"
       POSTGRES_USER: "servicedb_user"
       POSTGRES_PASSWORD: "servicedb_passwd"
    ports:
      - "80:5000"

  grpc-service:
    image: mgcrp/hw2_grpc:latest
    container_name: service-grpc
    environment:
       POSTGRES_HOST: "service-db"
       POSTGRES_DB: "servicedb"
       POSTGRES_USER: "servicedb_user"
       POSTGRES_PASSWORD: "servicedb_passwd"
    ports:
      - "50051:50051"
